spring.application.name=library-app

# database property
spring.datasource.url=jdbc:mysql://localhost:3306/libapp
spring.datasource.username=root
spring.datasource.password=root12

spring.jpa.hibernate.ddl-auto=update